### ISSUE TITLE
Rollup replaces output file

### ISSUE THREAD

**Issue by ramanarupa** [elycruz/rollup-plugin-sass#130]
when I'm trying to use such configuration, rollup replaces sass output file by file which generated by rollup itself

```
import sass from 'rollup-plugin-sass';

export default [
  {
    input: 'App/sass/index.scss',
    output: {
      file: 'myfile.css',
    },
    plugins: [
      sass({
        output: 'myfile.css,
        options: {
          outputStyle: 'compressed',
        },
      }),
    ],
  }
];
```

how to resolve this issue ?

**Comment by elycruz** [comment]
Currently the plugin doesn't support *.css files (the supported extensions are currently hard-coded in the plugin).

I've opened a new ticket for adding the ability to set the extensions the plugin recognizes at runtime (ticket no. below).

Please subscribe to #131 - The work will be performed via there.

**Comment by elycruz** [comment]
@ramanarupa Question, is it that the files are replaced with empty files, and/or are the files replaced but with "uncompressed" content?

**Comment by elycruz** [comment]
After looking at your code more closely it is clear that rollup overwrites your file because you have it listed as it's `output` file.  Additionally, we're not going to support pure *.css files, as part of our plugin, due to 'dart-sass' not supporting *.css imports (by default).  If you need pure css files support I recommended using 'postcss' (or one of the rollup compatible ones), in your build pipeline.
