### ISSUE TITLE
`--quiet -q` flag/option is not respected

### ISSUE THREAD

**Issue by jackblackCH** [elycruz/rollup-plugin-sass#60]
all `@warn` statements are still visible in the output.

**Comment by differui** [comment]
this plugin use [dart-sass](https://github.com/sass/dart-sass) as default sass compiler and `--quiet` flag/option not supported by it. try [node-sass](https://github.com/sass/node-sass) with [runtime](https://github.com/differui/rollup-plugin-sass#runtime) option :)

**Comment by jackblackCH** [comment]
Does not work either

**Comment by differui** [comment]
Hi @jackblackCH:

As comment from https://github.com/sass/node-sass/issues/2265#issuecomment-370198733. `--quiet` flag/option only for CLI.

**Comment by elycruz** [comment]
This option is now added to dart-sass (https://sass-lang.com/documentation/cli/dart-sass/#quiet).  Moving this to 'needs-triage'.

**Comment by elycruz** [comment]
So turns out the (`sass`) JS API doesn't support the `quiet` option (just the `quietDeps` option):

- https://sass-lang.com/documentation/js-api/types/legacyoptions/
- https://sass-lang.com/documentation/js-api/interfaces/legacyfileoptions/
- https://sass-lang.com/documentation/js-api/interfaces/legacystringoptions/
- https://sass-lang.com/documentation/js-api/interfaces/legacysharedoptions/

Closing this issue.
